// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjUCAKMqp6gafkd331Mwc_DgCWMFqEHKs',
    appId: '1:667732059074:web:fd9ba376e7262100da2c5b',
    messagingSenderId: '667732059074',
    projectId: 'proyecto-flutter-firebas-9a3ee',
    authDomain: 'proyecto-flutter-firebas-9a3ee.firebaseapp.com',
    storageBucket: 'proyecto-flutter-firebas-9a3ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3iEgxFnI_blxWclkp6VaneZWwZe10RZo',
    appId: '1:667732059074:android:0c928decff90b161da2c5b',
    messagingSenderId: '667732059074',
    projectId: 'proyecto-flutter-firebas-9a3ee',
    storageBucket: 'proyecto-flutter-firebas-9a3ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCWbu23iAWz3u-2WQ1ZTwbYx7iX4uFk6c',
    appId: '1:667732059074:ios:16ddb8841e08fc3cda2c5b',
    messagingSenderId: '667732059074',
    projectId: 'proyecto-flutter-firebas-9a3ee',
    storageBucket: 'proyecto-flutter-firebas-9a3ee.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutterFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCWbu23iAWz3u-2WQ1ZTwbYx7iX4uFk6c',
    appId: '1:667732059074:ios:16ddb8841e08fc3cda2c5b',
    messagingSenderId: '667732059074',
    projectId: 'proyecto-flutter-firebas-9a3ee',
    storageBucket: 'proyecto-flutter-firebas-9a3ee.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFlutterFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjUCAKMqp6gafkd331Mwc_DgCWMFqEHKs',
    appId: '1:667732059074:web:d80594378945f0f8da2c5b',
    messagingSenderId: '667732059074',
    projectId: 'proyecto-flutter-firebas-9a3ee',
    authDomain: 'proyecto-flutter-firebas-9a3ee.firebaseapp.com',
    storageBucket: 'proyecto-flutter-firebas-9a3ee.firebasestorage.app',
  );

}